import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ perfil}) {
  return (
    <>
      <Head>
        <title>Meu Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <a href="/">Home</a>
          <a href="/projects">Projetos</a>
        </nav>
      </header>

      <main className={styles.main}>
        <h1>{perfil.name}</h1>
        <p>{perfil.about}</p>
        <p>{perfil.abilities}</p>
        <a href={perfil.links.github}>GitHub</a>
        <a href={perfil.links.linkedin}>LinkedIn</a>
      </main>

      <footer> @Copyright 2023</footer>
    </>
  )
}

export async function getStaticProps() {
  const data = await import('../data/data.json');
  const perfil = data.perfil;
  
  return {
    props: { perfil }
  }
}
