import Head from 'next/head'
import { Inter } from 'next/font/google'
import { HomePage } from '@/components/homepage'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ perfil }) {
  return (
    <>
      <Head>
        <title>Meu Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage perfil={perfil} />
    </>
  )
}

export async function getStaticProps() {
    const data = await import('../data/data.json');
    const perfil = data.perfil;
    
    return {
      props: { perfil }
    }
}
