import Head from "next/head"
import { Footer } from "./footer"
import { Header } from "./header"

export const MainLayout = ({children}) => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>Meu Portfólio</title>
            </Head>
            <Header />
            <main>
                {children}
            </main>
            <Footer />
        </>
    )
}