import Head from "next/head"
import { Footer } from "./footer"
import { Header } from "./header"
import { useState, useEffect } from "react"

/*
    Main Layout contendo os componentes em comum de todas páginas da aplicação. Recebe como parâmetro o
    conteúdo específico da página.
*/

export const MainLayout = ({children}) => {
    const [showButton, setShowButton] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            if (window.scrollY > 200) {
                setShowButton(true);
            } else {
                setShowButton(false);
            }
        };

        window.addEventListener('scroll', handleScroll);
        
        // Clean up
        return () => {
            window.removeEventListener('scroll', handleScroll);
        };
    }, []);

    const scrollToTop = () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    };

    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>Meu Portfólio</title>
            </Head>
            <Header />
            <main>
                {children}
            </main>
            <Footer />
            {showButton && (
                <button 
                    className="scroll-to-top"
                    onClick={scrollToTop}
                    aria-label="Voltar ao topo"
                >
                    <i className='bx bx-up-arrow-alt'></i>
                </button>
            )}
        </>
    )
}